# Permalinks
permalink:           pretty

# Setup
title:               Dr. G's Blog
tagline:             A blog about data, science, and...
url:                 https://pagiesting.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Paul Giesting
  url:               https://twitter.com/infamous_DrG
  email:             pagiesti@gmail.com

# Custom vars
version:
#github:              PAGiesting
  repo:              https://github.com/PAGiesting/PAGiesting.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
